#include "../pipeline/pipeline.hpp"
#include "commands.hpp"

#include <filesystem>
#include <fstream>
#include <iostream>

namespace zith::cli::commands {

int cmd_new(const std::string &project_name, bool verbose) {
    namespace fs = std::filesystem;

    const fs::path root = fs::path(project_name).filename();
    if (fs::exists(root)) {
        zith::cli::pipeline::print_error("Directory '" + root.string() + "' already exists");
        return 1;
    }

    fs::create_directories(root / "src");
    fs::create_directories(root / "asset");
    fs::create_directories(root / "docs");
    fs::create_directories(root / ".zmodules");
    fs::create_directories(root / "tests");

    if (verbose) {
        zith::cli::pipeline::print_info("Created project structure: " + root.string());
    }

    {
        std::ofstream toml(root / "ZithProject.toml");
        if (!toml) {
            zith::cli::pipeline::print_error("Failed to create ZithProject.toml");
            return 1;
        }
        toml << "# ZithProject.toml — generated by 'zith new " << project_name << "'\n";
        toml << "\n";
        toml << "[project]\n";
        toml << "name = \"" << project_name << "\"\n";
        toml << "version = \"0.1.0\"\n";
        toml << "description = \"\"\n";
        toml << "authors = \"\"\n";
        toml << "license = \"MIT\"\n";
        toml << "homepage = \"\"\n";
        toml << "\n";
        toml << "[build]\n";
        toml << "entry = \"src/main.zith\"\n";
        toml << "output = \"bin/" << project_name << "\"\n";
        toml << "mode = \"debug\"\n";
        toml << "edition = \"2024\"\n";
        toml << "opt_level = 0\n";
        toml << "debug_level = 2\n";
        toml << "\n";
        toml << "[paths]\n";
        toml << "src_dir = \"src\"\n";
        toml << "bin_dir = \"target\"\n";
        toml << "mod_dir = \".zmodules\"\n";
        toml << "docs_dir = \"docs\"\n";
        toml << "test_dir = \"test\"\n";
        toml << "cache_dir = \".zcache\"\n";
        toml << "\n";
        toml << "# Optional: dependencies, link_libs, include_dirs, etc.\n";
    }

    {
        std::ofstream main_zith(root / "src" / "main.zt");
        if (!main_zith) {
            zith::cli::pipeline::print_error("Failed to create src/main.zt");
            return 1;
        }
        main_zith << "// " << project_name << " — main entry point\n";
        main_zith << "// Generated by 'zith new " << project_name << "'\n";
        main_zith << "\nfrom std/io/console;\n\n";
        main_zith << "fn main() {\n";
        main_zith << "    // TODO: your code here\n";
        main_zith << "    println(\"Hello from " << project_name << "!\")\n";
        main_zith << "}\n";
    }

    zith::cli::pipeline::print_success("Created project", root.string());
    if (verbose) {
        std::cout << "  cd " << root.string() << " && zith build\n";
    }
    return 0;
}

int cmd_clean(bool /*verbose*/) {
    zith::cli::pipeline::print_not_implemented("clean");
    return 1;
}

} // namespace zith::cli::commands
