#include "cli/commands.hpp"
#include "cli/terminal.hpp"
#include "diagnostics/color.hpp"

#include <cstdio>
#include <filesystem>
#include <fstream>
#include <string>

namespace zith::cli::commands {

#define CERR(c) term::err(TERM, diagnostics::ansi::c.data())
#define RERR   term::err_rst(TERM)
#define COUT(c) term::out(TERM, diagnostics::ansi::c.data())
#define ROUT   term::out_rst(TERM)

int cmd_new(const Options &opts) {
    auto TERM = term::init(opts);
    const std::string &name = opts.subcommand_arg;
    if (name.empty()) {
        std::fprintf(stderr, "%s[error]%s project name required\n", CERR(red), RERR);
        return 1;
    }

    namespace fs        = std::filesystem;
    const fs::path root = fs::path(name).filename();
    if (fs::exists(root)) {
        std::fprintf(stderr, "%s[error]%s directory '%s' already exists\n", CERR(red), RERR,
                     root.string().c_str());
        return 1;
    }

    fs::create_directories(root / "src");
    fs::create_directories(root / "assets");
    fs::create_directories(root / "docs");
    fs::create_directories(root / ".zmodules");
    fs::create_directories(root / "tests");

    if (opts.verbose)
        std::printf("%s[*]%s Created project structure: %s\n", COUT(cyan), ROUT,
                    root.string().c_str());

    {
        std::ofstream toml(root / "ZithProject.toml");
        if (!toml) {
            std::fprintf(stderr, "%s[error]%s failed to create ZithProject.toml\n", CERR(red),
                         RERR);
            return 1;
        }
        toml << "# ZithProject.toml -- generated by 'zithc new " << name << "'\n";
        toml << "\n";
        toml << "[project]\n";
        toml << "name = \"" << name << "\"\n";
        toml << "version = \"0.1.0\"\n";
        toml << "description = \"\"\n";
        toml << "authors = \"\"\n";
        toml << "license = \"MIT\"\n";
        toml << "homepage = \"\"\n";
        toml << "\n";
        toml << "[build]\n";
        toml << "entry = \"src/main.zith\"\n";
        toml << "output = \"bin/" << name << "\"\n";
        toml << "mode = \"debug\"\n";
        toml << "opt_level = 0\n";
        toml << "\n";
        toml << "[paths]\n";
        toml << "src_dir = [\"src\"]\n";
        toml << "asset_dir = \"assets\"\n";
        toml << "bin_dir = \"target\"\n";
        toml << "mod_dir = \".zmodules\"\n";
        toml << "docs_dir = \"docs\"\n";
        toml << "test_dir = \"tests\"\n";
        toml << "\n";
    }

    {
        std::ofstream main_zith(root / "src" / "main.zith");
        if (!main_zith) {
            std::fprintf(stderr, "%s[error]%s failed to create src/main.zith\n", CERR(red), RERR);
            return 1;
        }
        main_zith << "// " << name << " -- main entry point\n";
        main_zith << "// Generated by 'zithc new " << name << "'\n";
        main_zith << "\n";
        main_zith << "from std/io/console\n\n";
        main_zith << "fn main(): i32 {\n";
        main_zith << "    // TODO: your code here\n";
        main_zith << "    // @ prefix macros\n";
        main_zith << "    @println(\"Hello from " << name << "!\")\n";
        main_zith << "    //implicit return 0";
        main_zith << "\n}\n";
    }

    std::printf("%s[ok]%s Created project: %s\n", COUT(green), ROUT, root.string().c_str());
    if (opts.verbose)
        std::printf("  %scd %s && zithc build%s\n", COUT(cyan), root.string().c_str(), ROUT);

    return 0;
}

int cmd_clean(const Options &opts) {
    auto TERM = term::init(opts);
    std::fprintf(stderr, "%s[soon]%s not implemented yet\n", CERR(yellow), RERR);
    return 1;
}

} // namespace zith::cli::commands
