#include "cli/commands.hpp"

#include <cstdio>
#include <filesystem>
#include <fstream>
#include <string>

namespace zith::cli::commands {

int cmd_new(const Options &opts) {
    const std::string &name = opts.subcommand_arg;
    if (name.empty()) {
        std::fprintf(stderr, "error: project name required\n");
        return 1;
    }

    namespace fs = std::filesystem;
    const fs::path root = fs::path(name).filename();
    if (fs::exists(root)) {
        std::fprintf(stderr, "error: directory '%s' already exists\n", root.c_str());
        return 1;
    }

    fs::create_directories(root / "src");
    fs::create_directories(root / "assets");
    fs::create_directories(root / "docs");
    fs::create_directories(root / ".zmodules");
    fs::create_directories(root / "tests");

    if (opts.verbose)
        std::printf("[*] Created project structure: %s\n", root.c_str());

    {
        std::ofstream toml(root / "ZithProject.toml");
        if (!toml) {
            std::fprintf(stderr, "error: failed to create ZithProject.toml\n");
            return 1;
        }
        toml << "# ZithProject.toml -- generated by 'zith new " << name << "'\n";
        toml << "\n";
        toml << "[project]\n";
        toml << "name = \"" << name << "\"\n";
        toml << "version = \"0.1.0\"\n";
        toml << "description = \"\"\n";
        toml << "authors = \"\"\n";
        toml << "license = \"MIT\"\n";
        toml << "homepage = \"\"\n";
        toml << "\n";
        toml << "[build]\n";
        toml << "entry = \"src/main.zith\"\n";
        toml << "output = \"bin/" << name << "\"\n";
        toml << "mode = \"debug\"\n";
        toml << "opt_level = 0\n";
        toml << "\n";
        toml << "[paths]\n";
        toml << "src_dir = \"src\"\n";
        toml << "bin_dir = \"target\"\n";
        toml << "mod_dir = \".zmodules\"\n";
        toml << "docs_dir = \"docs\"\n";
        toml << "test_dir = \"test\"\n";
        toml << "\n";
    }

    {
        std::ofstream main_zith(root / "src" / "main.zith");
        if (!main_zith) {
            std::fprintf(stderr, "error: failed to create src/main.zith\n");
            return 1;
        }
        main_zith << "// " << name << " -- main entry point\n";
        main_zith << "// Generated by 'zith new " << name << "'\n";
        main_zith << "\n";
        main_zith << "from std/io/console\n\n";
        main_zith << "fn main(): i32 {\n";
        main_zith << "    // TODO: your code here\n";
        main_zith << "    // @ prefix macros";
        main_zith << "    @println(\"Hello from " << name << "!\")\n";
        main_zith << "    //implicit return 0";
        main_zith << "}\n";
    }

    std::printf("[ok] Created project: %s\n", root.c_str());
    if (opts.verbose)
        std::printf("  cd %s && zith build\n", root.c_str());

    return 0;
}

int cmd_clean(const Options &opts) {
    (void)opts;
    std::fprintf(stderr, "[soon] not implemented yet\n");
    return 1;
}

} // namespace zith::cli::commands
