#include "cli/commands.hpp"
#include "cli/terminal.hpp"

#include <cstdio>
#include <filesystem>
#include <fstream>
#include <string>

namespace zith::cli::commands {

int create(const Options &opts) {
    auto TERM = term::init(opts);
    term::UsagePrinter out{stdout, TERM.coutOn};
    term::UsagePrinter err{stderr, TERM.cerrOn};
    const std::string &name = opts.subcommandStr;

    if (name.empty()) {
        err.red("[error]");
        std::fprintf(stderr, " project name required\n");
        return 1;
    }

    namespace fs        = std::filesystem;
    const fs::path root = fs::path(name).filename();
    if (fs::exists(root)) {
        err.red("[error]");
        std::fprintf(stderr, " directory '%s' already exists\n", root.string().c_str());
        return 1;
    }

    fs::create_directories(root / "src");
    fs::create_directories(root / "assets");
    fs::create_directories(root / "docs");
    fs::create_directories(root / ".zmodules");
    fs::create_directories(root / "tests");

    if (opts.flags.verbose()) {
        out.cyan("[*]");
        std::printf(" Created project structure: %s\n", root.string().c_str());
    }

    {
        std::ofstream toml(root / "ZithProject.toml");
        if (!toml) {
            err.red("[error]");
            std::fprintf(stderr, " failed to create ZithProject.toml\n");
            return 1;
        }
        toml << "# ZithProject.toml -- generated by 'zithc new " << name << "'\n";
        toml << "\n";
        toml << "[project]\n";
        toml << "name = \"" << name << "\"\n";
        toml << "version = \"0.1.0\"\n";
        toml << "description = \"\"\n";
        toml << "authors = \"\"\n";
        toml << "license = \"MIT\"\n";
        toml << "homepage = \"\"\n";
        toml << "\n";
        toml << "[build]\n";
        toml << "entry = \"src/main.zith\"\n";
        toml << "output = \"bin/" << name << "\"\n";
        toml << "mode = \"debug\"\n";
        toml << "opt_level = 0\n";
        toml << "\n";
        toml << "[paths]\n";
        toml << "src_dir = [\"src\"]\n";
        toml << "asset_dir = \"assets\"\n";
        toml << "bin_dir = \"target\"\n";
        toml << "mod_dir = \".zmodules\"\n";
        toml << "docs_dir = \"docs\"\n";
        toml << "test_dir = \"tests\"\n";
        toml << "\n";
    }

    {
        std::ofstream main_zith(root / "src" / "main.zith");
        if (!main_zith) {
            err.red("[error]");
            std::fprintf(stderr, " failed to create src/main.zith\n");
            return 1;
        }
        main_zith << "// " << name << " -- main entry point\n";
        main_zith << "// Generated by 'zithc new " << name << "'\n";
        main_zith << "\n";
        main_zith << "from std/io/console\n\n";
        main_zith << "fn main(): i32 {\n";
        main_zith << "    // TODO: your code here\n";
        main_zith << "    // @ prefix macros\n";
        main_zith << "    @println(\"Hello from " << name << "!\")\n";
        main_zith << "    //implicit return 0";
        main_zith << "\n}\n";
    }

    out.green("[ok]");
    std::printf(" Created project: %s\n", root.string().c_str());
    if (opts.flags.verbose()) {
        out.cyan("  cd");
        std::printf(" %s && zithc build\n", root.string().c_str());
    }

    return 0;
}

int clean(const Options &opts) {
    auto TERM = term::init(opts);
    term::UsagePrinter err{stderr, TERM.cerrOn};
    err.yellow("[soon]");
    std::fprintf(stderr, " not implemented yet\n");
    return 1;
}

} // namespace zith::cli::commands
