name: Clear All Caches

on:
  workflow_dispatch:  # Manually trigger from Actions tab

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Clear all caches
        run: |
          echo "Fetching list of all cache keys..."
          cacheKeys=$(gh cache list --limit 99999 --json id --jq '.[].id')
          
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeys
          do
            gh cache delete $cacheKey --confirm
          done
          echo "Done!"
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
