name: Clear All Caches

on:
  workflow_dispatch:

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Clear all caches
        run: |
          echo "Deleting all caches..."
          gh cache delete --all --succeed-on-no-caches
          echo "Done!"
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
